### ISSUE TITLE
double free or corruption (!prev) Aborted (core dumped)

### ISSUE THREAD

**Issue by ysh329** [ysh329/OpenCL-101#3]
```shell
*** Error in `./bandwidth': double free or corruption (!prev): 0x000000001c5dd650 ***
Aborted (core dumped)
```

**Comment by ysh329** [comment]
I think this problem is caused by using same `data_size` for declaration on host and device, such as using float-type on host but half-type on device.

**Comment by ysh329** [comment]
This really an strange issue! Now it was resolved by commented `free` function (relative.,maybe) at the end of program or other lines (I forgot).

**Comment by prettyannoying** [comment]
Hi, can you please give some details about how you resolved it? I have freed the memory as well, but I still keep getting the error.

**Comment by ysh329** [comment]
@skenypatel Hi, it's so long time ago. I think I forget `free` malloced variables.
