### ISSUE TITLE
May I ask how to display OpenCL on Streamline. My MaliG610 cannot be displayed on the Steamline in DS5.

### ISSUE THREAD

**Issue by Ybuzhenzhuo** [ysh329/OpenCL-101#63]
I execute the command gatrad on ARM. And created Test272config, where test272 is the program name. The content here is 
MALI-TIMELINE.ROLES=cl.
 MALI-TIMELINE.UDS LOSSLESS-MODE=1, 
MALI_GPU RENDERSTAGES ENABLE=1,

Afterwards, execute./gated. OpenCL is not displayed on Steamline.

**Comment by ysh329** [comment]
Excuse me, I have no more idea about Streamline.

**Comment by Ybuzhenzhuo** [comment]
> Excuse me, I have no more idea about Streamline.

https://github.com/ysh329/OpenCL-101/issues/38
大佬，这个帖子里面你怎么开启OpenCL模式的。是通过抓取G71的手机才有的吗。

**Comment by ysh329** [comment]
Too long time to remeber really.

**Comment by Ybuzhenzhuo** [comment]
> Too long time to remeber really.

It's okay, I'm looking for other methods. Thank you for your reply.

**Comment by Ybuzhenzhuo** [comment]
Boss, I'm back again. I would like to ask how to enable OpenCl mode on my phone. Can you reproduce the operation? I can pay the compensation.

**Comment by ysh329** [comment]
> Boss, I'm back again. I would like to ask how to enable OpenCl mode on my phone. Can you reproduce the operation? I can pay the compensation.

Welcome to my wechat group, detailed refer: https://github.com/ysh329/embedded-ai.bi-weekly/blob/master/wechat_qrcode.jpg.
